version: "3.9"
services:
  db:
    image: mysql:latest
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: bookmarker
      MYSQL_PASSWORD: bookmarker
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql/my.cnf:/etc/mysql/my.cnf
      - ./db/mysql/init:/docker-entrypoint-initdb.d